"""
ADK Companion - 工具集
"""

import os
import json
from pathlib import Path
from typing import Optional
from github import Github
from dotenv import load_dotenv
load_dotenv()

def find_adk_site_packages() -> Optional[Path]:
    """查找当前 Python 环境下 ADK 库的 site-packages 路径"""
    try:
        import google.adk
        adk_path = Path(google.adk.__file__).parent
        return adk_path
    except ImportError:
        return None

def read_adk_codebase(keyword: str, max_results: int = 10) -> list[str]:
    """在 ADK 源码中搜索关键词并返回匹配的文件内容片段"""
    adk_path = find_adk_site_packages()
    if not adk_path:
        return ["ADK 未安装在当前环境中"]
    
    results = []
    try:
        # 简单实现：遍历 .py 文件并搜索关键词
        for py_file in adk_path.rglob("*.py"):
            if len(results) >= max_results:
                break
            try:
                content = py_file.read_text(encoding="utf-8")
                if keyword.lower() in content.lower():
                    results.append(f"文件: {py_file.relative_to(adk_path)}\n{content[:500]}...")
            except Exception:
                continue
    except Exception as e:
        results.append(f"搜索出错: {e}")
    
    return results[:max_results]

def check_upstream_release() -> dict:
    """检查上游 ADK 仓库的最新发布版本"""
    try:
        # 使用 GitHub API 获取最新发布
        token = os.getenv("GITHUB_TOKEN")
        g = Github(token) if token else Github()
        repo = g.get_repo("google/adk-python")
        latest_release = repo.get_latest_release()
        
        return {
            "tag_name": latest_release.tag_name,
            "published_at": latest_release.published_at.isoformat(),
            "body": latest_release.body[:1000] + "..." if len(latest_release.body) > 1000 else latest_release.body
        }
    except Exception as e:
        return {"error": str(e)}

def generate_pr(
    title: str,
    description: str,
    files_to_modify: str = None,
    files_to_create: str = None,
    base_branch: str = "main",
    branch_prefix: str = "feature",
    target_repo: str = None
) -> dict:
    """
    通用 PR 生成器 - 直接对远程仓库创建 PR
    
    Args:
        title: PR 标题
        description: PR 描述
        files_to_modify: 要修改的文件字典 (JSON 字符串) {文件路径: 新内容}
        files_to_create: 要创建的文件字典 (JSON 字符串) {文件路径: 文件内容}
        base_branch: 目标分支（默认 main）
        branch_prefix: 分支前缀（默认 feature）
        target_repo: 目标仓库，格式为 "owner/repo"，如果不指定则尝试从环境获取
    
    Returns:
        dict: 包含 PR 信息或错误信息
    """
    try:
        from datetime import datetime
        
        if files_to_modify and isinstance(files_to_modify, str):
            files_to_modify = json.loads(files_to_modify)
        if files_to_create and isinstance(files_to_create, str):
            files_to_create = json.loads(files_to_create)
        
        # 检查 GitHub Token
        token = os.getenv("GITHUB_TOKEN")
        if not token:
            return {"error": "需要设置 GITHUB_TOKEN 环境变量"}
        
        # 确定目标仓库
        if not target_repo:
            return {"error": "需要指定 target_repo 参数，格式为 'owner/repo'"}
        
        # 验证仓库格式
        if '/' not in target_repo or len(target_repo.split('/')) != 2:
            return {"error": "target_repo 格式错误，应为 'owner/repo'"}
        
        g = Github(token)
        
        # 验证仓库存在且可访问
        try:
            github_repo = g.get_repo(target_repo)
        except Exception as e:
            return {"error": f"无法访问仓库 {target_repo}: {str(e)}"}
        
        # 如果没有文件操作，直接创建一个空的 PR
        if not files_to_modify and not files_to_create:
            try:
                # 创建一个简单的 PR（不涉及文件更改）
                pr = github_repo.create_pull(
                    title=title,
                    body=f"{description}\n\n---\nGenerated by ADK Companion at {datetime.now().isoformat()}",
                    head=base_branch,  # 使用同一分支作为源和目标
                    base=base_branch
                )
                return {
                    "status": "success",
                    "pr_url": pr.html_url,
                    "pr_number": pr.number,
                    "message": f"Created PR #{pr.number}: {title}"
                }
            except Exception as e:
                return {"error": f"创建 PR 失败: {str(e)}"}
        
        # 有文件操作时，需要通过 GitHub API 直接创建文件
        try:
            # 生成分支名
            safe_title = "".join(c for c in title if c.isalnum() or c in (' ', '-', '_')).rstrip()
            if not safe_title:
                safe_title = "update"
            branch_name = f"{branch_prefix}/{ '-'.join(safe_title.lower().split()[:5])}"
            
            # 获取基础分支的最新提交
            base_branch_ref = github_repo.get_branch(base_branch)
            base_sha = base_branch_ref.commit.sha
            
            # 创建新分支
            try:
                github_repo.create_git_ref(
                    ref=f"refs/heads/{branch_name}",
                    sha=base_sha
                )
            except Exception as e:
                if "already exists" in str(e):
                    # 分支已存在，删除后重新创建
                    try:
                        github_repo.get_git_ref(f"heads/{branch_name}").delete()
                        github_repo.create_git_ref(
                            ref=f"refs/heads/{branch_name}",
                            sha=base_sha
                        )
                    except Exception as delete_e:
                        return {"error": f"无法创建分支 {branch_name}: {str(delete_e)}"}
                else:
                    return {"error": f"无法创建分支 {branch_name}: {str(e)}"}
            
            # 更新或创建文件
            all_files_changed = []
            
            # 处理要修改的文件
            if files_to_modify:
                for file_path, new_content in files_to_modify.items():
                    try:
                        # 获取当前文件内容（如果存在）
                        try:
                            current_file = github_repo.get_contents(file_path, ref=base_branch)
                            github_repo.update_file(
                                path=file_path,
                                message=f"Update {file_path}",
                                content=new_content,
                                sha=current_file.sha,
                                branch=branch_name
                            )
                        except Exception:
                            # 文件不存在，创建新文件
                            github_repo.create_file(
                                path=file_path,
                                message=f"Create {file_path}",
                                content=new_content,
                                branch=branch_name
                            )
                        all_files_changed.append(file_path)
                    except Exception as e:
                        return {"error": f"处理文件 {file_path} 失败: {str(e)}"}
            
            # 处理要创建的文件
            if files_to_create:
                for file_path, content in files_to_create.items():
                    try:
                        github_repo.create_file(
                            path=file_path,
                            message=f"Add {file_path}",
                            content=content,
                            branch=branch_name
                        )
                        all_files_changed.append(file_path)
                    except Exception as e:
                        return {"error": f"创建文件 {file_path} 失败: {str(e)}"}
            
            # 创建 PR
            commit_message = f"""{title}\n\n{description}\n\n---\nGenerated by ADK Companion at {datetime.now().isoformat()}\nFiles changed: {', '.join(all_files_changed)}"""
            
            pr = github_repo.create_pull(
                title=title,
                body=commit_message,
                head=branch_name,
                base=base_branch
            )
            
            return {
                "status": "success",
                "pr_url": pr.html_url,
                "pr_number": pr.number,
                "branch_name": branch_name,
                "files_changed": all_files_changed,
                "message": f"Created PR #{pr.number}: {title}"
            }
            
        except Exception as e:
            return {"error": f"通过 GitHub API 操作失败: {str(e)}"}
    except Exception as e:
        return {"error": f"生成 PR 时出错: {str(e)}"}

def read_github_repo(
    file_path: str = None,
    branch: str = "main",
    max_files: int = 50
) -> dict:
    """
    读取 GitHub 仓库 "fgh23333/adk-companion" 的项目结构或指定文件内容
    
    Args:
        file_path: 指定文件路径（相对于仓库根目录），如果为空则返回目录结构
        branch: 分支名，默认为 main
        max_files: 最大文件数量限制（仅在读取目录结构时生效）
    
    Returns:
        dict: 包含文件结构或文件内容的字典
    """
    try:
        token = os.getenv("GITHUB_TOKEN")
        g = Github(token) if token else Github()
        
        repo_path = "fgh23333/adk-companion"
        
        # 获取仓库对象
        repo = g.get_repo(repo_path)
        
        if file_path:
            # 读取指定文件内容
            try:
                file_content = repo.get_contents(file_path, ref=branch)
                if file_content.type == "file":
                    return {
                        "file_path": file_path,
                        "content": file_content.decoded_content.decode('utf-8'),
                        "size": file_content.size,
                        "sha": file_content.sha
                    }
                else:
                    return {"error": f"'{file_path}' 是一个目录，不是文件"}
            except Exception as e:
                return {"error": f"读取文件 '{file_path}' 失败: {str(e)}"}
        else:
            # 获取目录结构
            try:
                file_tree = []
                contents = repo.get_contents("", ref=branch)
                
                def process_directory(contents, prefix="", depth=0):
                    if depth > 3 or len(file_tree) >= max_files:  # 限制深度和数量
                        return
                    
                    for content in contents:
                        if len(file_tree) >= max_files:
                            break
                            
                        if content.type == "dir":
                            file_tree.append({
                                "type": "dir",
                                "path": f"{prefix}{content.name}/",
                                "size": 0
                            })
                            
                            # 递归获取子目录内容（限制深度）
                            if depth < 2:
                                try:
                                    sub_contents = repo.get_contents(content.path, ref=branch)
                                    process_directory(sub_contents, f"{prefix}{content.name}/", depth + 1)
                                except:
                                    continue
                        else:
                            file_tree.append({
                                "type": "file",
                                "path": f"{prefix}{content.name}",
                                "size": content.size,
                                "sha": content.sha
                            })
                
                process_directory(contents)
                
                return {
                    "repo": repo_path,
                    "branch": branch,
                    "total_files": len([f for f in file_tree if f["type"] == "file"]),
                    "total_dirs": len([f for f in file_tree if f["type"] == "dir"]),
                    "file_tree": file_tree[:max_files]
                }
                
            except Exception as e:
                return {"error": f"获取目录结构失败: {str(e)}"}
                
    except Exception as e:
        return {"error": f"GitHub API 调用失败: {str(e)}"}

def generate_evolution_pr(target_version: str, sample_code: str, dependency_changes: str, target_repo: str = None) -> dict:
    """
    生成 ADK 升级 PR - 使用通用 PR 生成器的特化版本
    
    Args:
        target_version: 目标版本号
        sample_code: 示例代码内容
        dependency_changes: 依赖变更说明
        target_repo: 目标仓库，格式为 "owner/repo"
    """
    from datetime import datetime
    
    title = f"feat: upgrade to ADK {target_version}"
    description = f"""Upgrade google-adk to version {target_version}\n\nChanges:\n- Update google-adk to version {target_version}\n- Add new feature sample: new_feature_{target_version}.py\n\n{dependency_changes}"""
    
    # 修改 requirements.txt
    files_to_modify = {}
    requirements_path = "requirements.txt"
    if (Path(__file__).parent.parent.parent / requirements_path).exists():
        with open(Path(__file__).parent.parent.parent / requirements_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        lines = content.split('\n')
        updated_lines = []
        for line in lines:
            if line.startswith('google-adk'):
                updated_lines.append(f'google-adk=={target_version}')
            else:
                updated_lines.append(line)
        
        files_to_modify[requirements_path] = '\n'.join(updated_lines)
    
    # 创建示例文件
    files_to_create = {
        f"samples/new_feature_{target_version}.py": f'''"""\n新功能示例 - 版本 {target_version}\n生成时间: {datetime.now().isoformat()}\n"""\n\n{sample_code}\n\nif __name__ == "__main__":\n    # 示例用法\n    print("新功能示例运行完成")\n'''
    }
    
    return generate_pr(
        title=title,
        description=description,
        files_to_modify=json.dumps(files_to_modify) if files_to_modify else None,
        files_to_create=json.dumps(files_to_create) if files_to_create else None,
        branch_prefix="chore",
        target_repo=target_repo
    )

def review_pr(
    repo_path: str,
    pr_number: int,
    approve: bool = False,
    review_comment: str = None,
    token_env: str = "GITHUB_TOKEN"
) -> dict:
    """
    审查 PR 并可选择批准或添加评论
    
    Args:
        repo_path: 仓库路径，格式为 "owner/repo"
        pr_number: PR 编号
        approve: 是否批准 PR（默认 False）
        review_comment: 审查评论（可选）
        token_env: GitHub Token 环境变量名（默认 "GITHUB_TOKEN"）
    
    Returns:
        dict: 包含审查结果或错误信息
    """
    try:
        token = os.getenv(token_env)
        if not token:
            return {"error": f"需要设置 {token_env} 环境变量"}
        
        g = Github(token)
        repo = g.get_repo(repo_path)
        pr = repo.get_pull(pr_number)
        
        # 检查是否是自己的PR
        current_user = g.get_user()
        is_own_pr = pr.user.login == current_user.login
        
        if is_own_pr and approve:
            return {
                "error": "无法批准自己的PR",
                "pr_author": pr.user.login,
                "current_user": current_user.login,
                "token_used": token_env,
                "suggestion": "您可以：1) 使用 request_pr_review 请求其他用户审查，2) 只添加评论而不批准",
                "can_comment": True
            }
        
        # 获取 PR 文件变更
        files_changed = []
        for file in pr.get_files():
            files_changed.append({
                "filename": file.filename,
                "status": file.status,
                "additions": file.additions,
                "deletions": file.deletions,
                "changes": file.changes,
                "patch": file.patch[:1000] + "..." if len(file.patch) > 1000 else file.patch
            })
        
        # 获取 PR 详情
        pr_details = {
            "number": pr.number,
            "title": pr.title,
            "body": pr.body,
            "state": pr.state,
            "head_branch": pr.head.ref,
            "base_branch": pr.base.ref,
            "author": pr.user.login,
            "created_at": pr.created_at.isoformat(),
            "updated_at": pr.updated_at.isoformat(),
            "mergeable": pr.mergeable,
            "mergeable_state": pr.mergeable_state,
            "files_changed": files_changed,
            "commits": pr.commits,
            "additions": pr.additions,
            "deletions": pr.deletions,
            "changed_files": pr.changed_files
        }
        
        # 如果需要批准或添加评论
        if approve or review_comment:
            try:
                # 创建审查
                if approve:
                    pr.create_review(
                        body=review_comment or "LGTM! Approved by ADK Companion.",
                        event="APPROVE"
                    )
                    pr_details["review_action"] = "approved"
                elif review_comment:
                    pr.create_review(
                        body=review_comment,
                        event="COMMENT"
                    )
                    pr_details["review_action"] = "commented"
                    
            except Exception as e:
                return {"error": f"创建审查失败: {str(e)}"}
        
        return {
            "status": "success",
            "pr_details": pr_details,
            "token_used": token_env,
            "message": f"Successfully reviewed PR #{pr_number}"
        }
        
    except Exception as e:
        return {"error": f"审查 PR 失败: {str(e)}"}

def merge_pr(
    repo_path: str,
    pr_number: int,
    merge_method: str = "merge",
    commit_title: str = None,
    commit_message: str = None,
    token_env: str = "GITHUB_TOKEN"
) -> dict:
    """
    合并 PR
    
    Args:
        repo_path: 仓库路径，格式为 "owner/repo"
        pr_number: PR 编号
        merge_method: 合并方法，可选 "merge", "squash", "rebase"（默认 "merge"）
        commit_title: 合并提交标题（可选）
        commit_message: 合并提交消息（可选）
        token_env: GitHub Token 环境变量名（默认 "GITHUB_TOKEN"）
    
    Returns:
        dict: 包含合并结果或错误信息
    """
    try:
        token = os.getenv(token_env)
        if not token:
            return {"error": f"需要设置 {token_env} 环境变量"}
        
        g = Github(token)
        repo = g.get_repo(repo_path)
        pr = repo.get_pull(pr_number)
        
        # 检查 PR 是否可合并
        if not pr.mergeable:
            return {
                "error": "PR 不可合并",
                "mergeable_state": pr.mergeable_state,
                "status": pr.raw_data.get('status', 'unknown')
            }
        
        # 检查是否有合并冲突
        if pr.mergeable_state == "dirty":
            return {"error": "PR 有合并冲突，无法自动合并"}
        
        # 检查是否需要 CI 通过
        if pr.mergeable_state == "blocked":
            # 获取状态检查
            status_checks = []
            try:
                for commit in pr.get_commits():
                    for status in commit.get_status().statuses:
                        status_checks.append({
                            "context": status.context,
                            "state": status.state,
                            "description": status.description,
                            "target_url": status.target_url
                        })
            except Exception:
                pass
            
            return {
                "error": "PR 被阻止合并，可能需要 CI 检查通过或审查批准",
                "status_checks": status_checks
            }
        
        # 执行合并
        print(f"[DEBUG] 开始执行合并操作...")
        try:
            print(f"[DEBUG] 使用合并方法: {merge_method}")
            print(f"[DEBUG] 提交信息: {commit_message}")
            if commit_title:
                print(f"[DEBUG] 提交标题: {commit_title}")
            
            merge_result = pr.merge(
                commit_message=commit_message,
                commit_title=commit_title,
                merge_method=merge_method
            )
            
            print(f"[DEBUG] 合并操作成功完成")
            print(f"[DEBUG] merge_result.merged: {merge_result.merged}")
            print(f"[DEBUG] merge_result.sha: {merge_result.sha}")
            print(f"[DEBUG] merge_result.message: {merge_result.message}")
            
            return {
                "status": "success",
                "merged": merge_result.merged,
                "sha": merge_result.sha,
                "message": merge_result.message,
                "pr_number": pr_number,
                "merge_method": merge_method,
                "merged_at": merge_result.merged_at.isoformat() if hasattr(merge_result, "merged_at") and merge_result.merged_at else None,
                "token_used": token_env
            }
            
        except Exception as e:
            print(f"[DEBUG] 合并操作发生异常")
            print(f"[DEBUG] 异常对象: {e}")
            print(f"[DEBUG] 异常类型: {type(e).__name__}")
            print(f"[DEBUG] 异常repr: {repr(e)}")
            print(f"[DEBUG] 异常args: {getattr(e, 'args', 'No args')}")
            
            # 尝试获取更详细的错误信息
            error_msg = None
            try:
                error_msg = str(e)
                print(f"[DEBUG] str(e) = {error_msg}")
            except Exception as str_err:
                print(f"[DEBUG] str(e) 也失败: {str_err}")
                error_msg = f"异常无法转换为字符串 (类型: {type(e).__name__})"
            
            # 检查是否有 PyGithub 特有的属性
            if hasattr(e, 'data'):
                print(f"[DEBUG] 异常data: {e.data}")
            if hasattr(e, 'status'):
                print(f"[DEBUG] 异常status: {e.status}")
            if hasattr(e, 'headers'):
                print(f"[DEBUG] 异常headers: {e.headers}")
            
            # 提供更详细的错误信息
            if error_msg and "Required status check" in error_msg:
                print(f"[DEBUG] 识别错误: 必需的状态检查未通过")
                return {"error": "合并失败：必需的状态检查未通过"}
            elif error_msg and "Review required" in error_msg:
                print(f"[DEBUG] 识别错误: 需要代码审查")
                return {"error": "合并失败：需要代码审查"}
            elif error_msg and "not authorized" in error_msg.lower():
                print(f"[DEBUG] 识别错误: 没有权限")
                return {"error": "合并失败：没有权限合并此 PR"}
            elif error_msg and "merge conflict" in error_msg.lower():
                print(f"[DEBUG] 识别错误: 合并冲突")
                return {"error": "合并失败：存在合并冲突"}
            else:
                print(f"[DEBUG] 未识别的错误类型，构造详细错误信息")
                detailed_error = f"合并失败: {error_msg if error_msg else '未知错误'} (类型: {type(e).__name__})"
                return {"error": detailed_error}
        
    except Exception as e:
        print(f"[DEBUG] 外层异常捕获")
        print(f"[DEBUG] 外层异常对象: {e}")
        print(f"[DEBUG] 外层异常类型: {type(e).__name__}")
        print(f"[DEBUG] 外层异常repr: {repr(e)}")
        
        # 尝试安全地获取错误信息
        error_msg = "未知外层异常"
        try:
            error_msg = str(e)
        except Exception:
            error_msg = f"外层异常无法转换为字符串 (类型: {type(e).__name__})"
        
        return {"error": f"合并 PR 失败: {error_msg}"}

def check_pr_author(repo_path: str, pr_number: int, token_env: str = "GITHUB_TOKEN") -> dict:
    """
    检查 PR 的创建者信息
    
    Args:
        repo_path: 仓库路径，格式为 "owner/repo"
        pr_number: PR 编号
        token_env: GitHub Token 环境变量名（默认 "GITHUB_TOKEN"）
    
    Returns:
        dict: 包含 PR 作者信息和当前用户信息
    """
    try:
        # 参数验证
        if not repo_path or not isinstance(repo_path, str):
            return {"error": "repo_path 必须是有效的字符串，格式为 'owner/repo'"}
        
        if not pr_number or not isinstance(pr_number, int):
            return {"error": "pr_number 必须是有效的整数"}
        
        if not token_env or not isinstance(token_env, str):
            return {"error": "token_env 必须是有效的字符串"}
        
        token = os.getenv(token_env)
        if not token:
            return {"error": f"需要设置 {token_env} 环境变量"}
        
        g = Github(token)
        repo = g.get_repo(repo_path)
        pr = repo.get_pull(pr_number)
        
        # 获取当前用户信息
        current_user = g.get_user()
        
        # 检查是否是自己的PR
        is_own_pr = pr.user.login == current_user.login
        
        return {
            "status": "success",
            "pr_number": pr_number,
            "pr_author": pr.user.login,
            "current_user": current_user.login,
            "is_own_pr": is_own_pr,
            "pr_title": pr.title,
            "pr_state": pr.state,
            "can_approve": not is_own_pr,
            "token_used": token_env,
            "message": "这是您自己的PR，无法自己批准" if is_own_pr else "可以批准此PR"
        }
        
    except Exception as e:
        return {"error": f"检查 PR 作者失败: {str(e)}"}

def request_pr_review(repo_path: str, pr_number: int, reviewers: str = None, team_reviewers: str = None, token_env: str = "GITHUB_TOKEN") -> dict:
    """
    请求其他用户审查 PR
    
    Args:
        repo_path: 仓库路径，格式为 "owner/repo"
        pr_number: PR 编号
        reviewers: 审查者用户名列表 (JSON 字符串)（可选）
        team_reviewers: 团队审查者列表 (JSON 字符串)（可选）
        token_env: GitHub Token 环境变量名（默认 "GITHUB_TOKEN"）
    
    Returns:
        dict: 包含请求结果或错误信息
    """
    try:
        if reviewers and isinstance(reviewers, str):
            reviewers = json.loads(reviewers)
        if team_reviewers and isinstance(team_reviewers, str):
            team_reviewers = json.loads(team_reviewers)
        token = os.getenv(token_env)
        if not token:
            return {"error": f"需要设置 {token_env} 环境变量"}
        
        g = Github(token)
        repo = g.get_repo(repo_path)
        pr = repo.get_pull(pr_number)
        
        # 检查是否是自己的PR
        current_user = g.get_user()
        is_own_pr = pr.user.login == current_user.login
        
        if not is_own_pr:
            return {"error": "只能请求审查自己的PR"}
        
        # 如果没有指定审查者，尝试获取仓库的贡献者
        if not reviewers and not team_reviewers:
            try:
                contributors = [contributor.login for contributor in repo.get_contributors()]
                # 排除自己
                contributors = [user for user in contributors if user != current_user.login]
                if contributors:
                    reviewers = contributors[:3]  # 最多请求3个审查者
            except Exception:
                pass
        
        if not reviewers and not team_reviewers:
            return {"error": "没有可用的审查者，请手动指定 reviewers 或 team_reviewers 参数"}
        
        # 创建审查请求
        try:
            pr.create_review_request(reviewers=reviewers, team_reviewers=team_reviewers)
            
            return {
                "status": "success",
                "pr_number": pr_number,
                "requested_reviewers": reviewers or [],
                "requested_team_reviewers": team_reviewers or [],
                "token_used": token_env,
                "message": f"已请求审查 PR #{pr_number}"
            }
            
        except Exception as e:
            error_msg = str(e)
            if "Review cannot be requested" in error_msg:
                return {"error": "无法请求审查，可能是因为PR作者没有权限或审查者不可用"}
            else:
                return {"error": f"请求审查失败: {error_msg}"}
        
    except Exception as e:
        return {"error": f"请求 PR 审查失败: {str(e)}"}

def list_prs(
    repo_path: str,
    state: str = "open",
    sort: str = "created",
    direction: str = "desc",
    limit: int = 20,
    token_env: str = "GITHUB_TOKEN"
) -> dict:
    """
    列出仓库的 PR
    
    Args:
        repo_path: 仓库路径，格式为 "owner/repo"
        state: PR 状态，可选 "open", "closed", "all"（默认 "open"）
        sort: 排序方式，可选 "created", "updated", "popularity"（默认 "created"）
        direction: 排序方向，可选 "asc", "desc"（默认 "desc"）
        limit: 最大返回数量（默认 20）
        token_env: GitHub Token 环境变量名（默认 "GITHUB_TOKEN"）
    
    Returns:
        dict: 包含 PR 列表或错误信息
    """
    try:
        token = os.getenv(token_env)
        g = Github(token) if token else Github()
        repo = g.get_repo(repo_path)
        
        # 获取 PR 列表
        pulls = repo.get_pulls(state=state, sort=sort, direction=direction)
        
        pr_list = []
        count = 0
        for pr in pulls:
            if count >= limit:
                break
                
            pr_info = {
                "number": pr.number,
                "title": pr.title,
                "body": pr.body[:200] + "..." if pr.body and len(pr.body) > 200 else pr.body,
                "state": pr.state,
                "head_branch": pr.head.ref,
                "base_branch": pr.base.ref,
                "author": pr.user.login,
                "created_at": pr.created_at.isoformat(),
                "updated_at": pr.updated_at.isoformat(),
                "mergeable": pr.mergeable,
                "mergeable_state": pr.mergeable_state,
                "commits": pr.commits,
                "additions": pr.additions,
                "deletions": pr.deletions,
                "changed_files": pr.changed_files,
                "url": pr.html_url
            }
            
            # 获取审查状态
            try:
                reviews = pr.get_reviews()
                approvals = sum(1 for review in reviews if review.state == "APPROVED")
                changes_requested = sum(1 for review in reviews if review.state == "CHANGES_REQUESTED")
                
                pr_info["review_status"] = {
                    "approvals": approvals,
                    "changes_requested": changes_requested,
                    "total_reviews": reviews.totalCount
                }
            except Exception:
                pr_info["review_status"] = {"approvals": 0, "changes_requested": 0, "total_reviews": 0}
            
            pr_list.append(pr_info)
            count += 1
        
        return {
            "status": "success",
            "repo": repo_path,
            "state": state,
            "total_prs": len(pr_list),
            "prs": pr_list,
            "token_used": token_env
        }
        
    except Exception as e:
        return {"error": f"获取 PR 列表失败: {str(e)}"}

def smart_review_pr(
    repo_path: str,
    pr_number: int,
    auto_merge: bool = True,
    merge_method: str = "merge",
    token_env: str = "GITHUB_TOKEN"
) -> dict:
    """
    智能 PR 审查工具 - 自动审查 PR 并决定是否合并或提出修改建议
    
    Args:
        repo_path: 仓库路径，格式为 "owner/repo"
        pr_number: PR 编号
        auto_merge: 是否在审查通过后自动合并（默认 True）
        merge_method: 合并方法，可选 "merge", "squash", "rebase"（默认 "merge"）
        token_env: GitHub Token 环境变量名（默认 "GITHUB_TOKEN"）
    
    Returns:
        dict: 包含审查结果和执行操作的详细信息
    """
    try:
        # 参数验证
        if not repo_path or not isinstance(repo_path, str):
            return {"error": "repo_path 必须是有效的字符串，格式为 'owner/repo'"}
        
        if not pr_number or not isinstance(pr_number, int):
            return {"error": "pr_number 必须是有效的整数"}
        
        if not token_env or not isinstance(token_env, str):
            return {"error": "token_env 必须是有效的字符串"}
        
        if merge_method not in ["merge", "squash", "rebase"]:
            return {"error": "merge_method 必须是 'merge', 'squash', 或 'rebase'"}
        
        # 首先检查 PR 作者信息
        author_check = check_pr_author(repo_path, pr_number, token_env)
        if "error" in author_check:
            return author_check
        
        # 获取 PR 详细信息进行审查
        token = os.getenv(token_env)
        if not token:
            return {"error": f"需要设置 {token_env} 环境变量"}
        
        g = Github(token)
        repo = g.get_repo(repo_path)
        pr = repo.get_pull(pr_number)
        
        # 收集 PR 信息用于审查
        files_info = []
        total_additions = 0
        total_deletions = 0
        
        for file in pr.get_files():
            file_info = {
                "filename": file.filename,
                "status": file.status,
                "additions": file.additions,
                "deletions": file.deletions,
                "changes": file.changes,
                "patch": file.patch[:2000] + "..." if len(file.patch) > 2000 else file.patch
            }
            files_info.append(file_info)
            total_additions += file.additions
            total_deletions += file.deletions
        
        # 构建 PR 摘要
        pr_summary = {
            "number": pr.number,
            "title": pr.title,
            "body": pr.body,
            "author": pr.user.login,
            "state": pr.state,
            "head_branch": pr.head.ref,
            "base_branch": pr.base.ref,
            "mergeable": pr.mergeable,
            "mergeable_state": pr.mergeable_state,
            "commits": pr.commits,
            "additions": total_additions,
            "deletions": total_deletions,
            "changed_files": pr.changed_files,
            "files": files_info,
            "is_own_pr": author_check["is_own_pr"]
        }
        
        # 执行智能审查逻辑
        review_result = _perform_intelligent_review(json.dumps(pr_summary), repo)
        
        # 根据审查结果执行相应操作
        if review_result["decision"] == "approve_and_merge" and auto_merge:
            # 尝试合并 PR
            merge_result = merge_pr(
                repo_path=repo_path,
                pr_number=pr_number,
                merge_method=merge_method,
                commit_title=f"Merge PR #{pr_number}: {pr.title}",
                commit_message=f"Auto-merged after review: {review_result['summary']}",
                token_env=token_env
            )
            
            if merge_result.get("status") == "success":
                return {
                    "status": "success",
                    "action": "approved_and_merged",
                    "pr_number": pr_number,
                    "review_summary": review_result,
                    "merge_result": merge_result,
                    "token_used": token_env,
                    "message": f"PR #{pr_number} 已通过审查并自动合并"
                }
            else:
                # 合并失败，添加审查评论但不合并
                comment = f"✅ 审查通过，但自动合并失败：{merge_result.get('error', '未知错误')}\n\n{review_result['summary']}"
                review_result = review_pr(repo_path, pr_number, approve=False, review_comment=comment, token_env=token_env)
                return {
                    "status": "partial_success",
                    "action": "approved_but_merge_failed",
                    "pr_number": pr_number,
                    "review_summary": review_result,
                    "merge_error": merge_result.get("error"),
                    "message": f"PR #{pr_number} 审查通过但合并失败，已添加评论"
                }
        
        elif review_result["decision"] == "request_changes":
            # 要求修改，添加详细评论
            comment = f"❌ 需要修改\n\n{review_result['summary']}\n\n**修改建议：**\n{review_result['suggestions']}"
            review_result = review_pr(repo_path, pr_number, approve=False, review_comment=comment, token_env=token_env)
            return {
                "status": "changes_requested",
                "action": "requested_changes",
                "pr_number": pr_number,
                "review_summary": review_result,
                "review_result": review_result,
                "message": f"PR #{pr_number} 需要修改，已添加详细评论"
            }
        
        elif review_result["decision"] == "request_human_review":
            # 请求人工审查
            if pr_summary["is_own_pr"]:
                # 如果是自己的PR，请求其他用户审查
                request_result = request_pr_review(repo_path, pr_number, token_env=token_env)
                comment = f"🤔 需要人工审查\n\n{review_result['summary']}\n\n已请求其他用户协助审查。"
            else:
                # 如果不是自己的PR，添加评论请求更多审查
                comment = f"🤔 需要进一步审查\n\n{review_result['summary']}\n\n建议请求其他维护者参与审查。"
                request_result = {"status": "commented"}
            
            review_result = review_pr(repo_path, pr_number, approve=False, review_comment=comment, token_env=token_env)
            return {
                "status": "human_review_requested",
                "action": "requested_human_review",
                "pr_number": pr_number,
                "review_summary": review_result,
                "request_result": request_result,
                "review_result": review_result,
                "message": f"PR #{pr_number} 需要人工审查，已处理"
            }
        
        else:
            return {
                "status": "review_completed",
                "action": "review_only",
                "pr_number": pr_number,
                "review_summary": review_result,
                "message": f"PR #{pr_number} 审查完成"
            }
            
    except Exception as e:
        return {"error": f"智能审查失败: {str(e)}"}

def review_pr_with_review_token(
    repo_path: str,
    pr_number: int,
    approve: bool = False,
    review_comment: str = None
) -> dict:
    """
    使用审查专用Token的 PR 审查工具
    
    Args:
        repo_path: 仓库路径，格式为 "owner/repo"
        pr_number: PR 编号
        approve: 是否批准 PR（默认 False）
        review_comment: 审查评论（可选）
    
    Returns:
        dict: 包含审查结果或错误信息
    """
    try:
        # 参数验证
        if not repo_path or not isinstance(repo_path, str):
            return {"error": "repo_path 必须是有效的字符串，格式为 'owner/repo'"}
        
        if not pr_number or not isinstance(pr_number, int):
            return {"error": "pr_number 必须是有效的整数"}
        
        # 使用审查专用Token
        token_env = "REVIEW_GITHUB_TOKEN"
        token = os.getenv(token_env)
        if not token:
            return {"error": f"需要设置 {token_env} 环境变量"}
        
        g = Github(token)
        repo = g.get_repo(repo_path)
        pr = repo.get_pull(pr_number)
        
        # 检查是否是自己的PR
        current_user = g.get_user()
        is_own_pr = pr.user.login == current_user.login
        
        if is_own_pr and approve:
            return {
                "error": "无法批准自己的PR",
                "pr_author": pr.user.login,
                "current_user": current_user.login,
                "token_used": token_env,
                "suggestion": "您可以：1) 使用 request_pr_review 请求其他用户审查，2) 只添加评论而不批准",
                "can_comment": True
            }
        
        # 获取 PR 文件变更
        files_changed = []
        for file in pr.get_files():
            files_changed.append({
                "filename": file.filename,
                "status": file.status,
                "additions": file.additions,
                "deletions": file.deletions,
                "changes": file.changes,
                "patch": file.patch[:1000] + "..." if len(file.patch) > 1000 else file.patch
            })
        
        # 获取 PR 详情
        pr_details = {
            "number": pr.number,
            "title": pr.title,
            "body": pr.body,
            "state": pr.state,
            "head_branch": pr.head.ref,
            "base_branch": pr.base.ref,
            "author": pr.user.login,
            "created_at": pr.created_at.isoformat(),
            "updated_at": pr.updated_at.isoformat(),
            "mergeable": pr.mergeable,
            "mergeable_state": pr.mergeable_state,
            "files_changed": files_changed,
            "commits": pr.commits,
            "additions": pr.additions,
            "deletions": pr.deletions,
            "changed_files": pr.changed_files
        }
        
        # 如果需要批准或添加评论
        if approve or review_comment:
            try:
                # 创建审查
                if approve:
                    pr.create_review(
                        body=review_comment or "LGTM! Approved by ADK Companion.",
                        event="APPROVE"
                    )
                    pr_details["review_action"] = "approved"
                elif review_comment:
                    pr.create_review(
                        body=review_comment,
                        event="COMMENT"
                    )
                    pr_details["review_action"] = "commented"
                    
            except Exception as e:
                return {"error": f"创建审查失败: {str(e)}"}
        
        return {
            "status": "success",
            "pr_details": pr_details,
            "token_used": token_env,
            "message": f"Successfully reviewed PR #{pr_number}"
        }
        
    except Exception as e:
        return {"error": f"审查 PR 失败: {str(e)}"}

def merge_pr_with_review_token(
    repo_path: str,
    pr_number: int,
    merge_method: str = "merge",
    commit_title: str = None,
    commit_message: str = None
) -> dict:
    """
    使用审查专用Token的 PR 合并工具
    
    Args:
        repo_path: 仓库路径，格式为 "owner/repo"
        pr_number: PR 编号
        merge_method: 合并方法，可选 "merge", "squash", "rebase"（默认 "merge"）
        commit_title: 合并提交标题（可选）
        commit_message: 合并提交消息（可选）
    
    Returns:
        dict: 包含合并结果或错误信息
    """
    try:
        # 参数验证
        if not repo_path or not isinstance(repo_path, str):
            return {"error": "repo_path 必须是有效的字符串，格式为 'owner/repo'"}
        
        if not pr_number or not isinstance(pr_number, int):
            return {"error": "pr_number 必须是有效的整数"}
        
        if merge_method not in ["merge", "squash", "rebase"]:
            return {"error": "merge_method 必须是 'merge', 'squash', 或 'rebase'"}
        
        # 使用审查专用Token
        token_env = "REVIEW_GITHUB_TOKEN"
        token = os.getenv(token_env)
        if not token:
            return {"error": f"需要设置 {token_env} 环境变量"}
        
        g = Github(token)
        repo = g.get_repo(repo_path)
        pr = repo.get_pull(pr_number)
        
        # 检查 PR 是否可合并
        if not pr.mergeable:
            return {
                "error": "PR 不可合并",
                "mergeable_state": pr.mergeable_state,
                "status": pr.raw_data.get('status', 'unknown')
            }
        
        # 检查是否有合并冲突
        if pr.mergeable_state == "dirty":
            return {"error": "PR 有合并冲突，无法自动合并"}
        
        # 检查是否需要 CI 通过
        if pr.mergeable_state == "blocked":
            # 获取状态检查
            status_checks = []
            try:
                for commit in pr.get_commits():
                    for status in commit.get_status().statuses:
                        status_checks.append({
                            "context": status.context,
                            "state": status.state,
                            "description": status.description,
                            "target_url": status.target_url
                        })
            except Exception:
                pass
            
            return {
                "error": "PR 被阻止合并，可能需要 CI 检查通过或审查批准",
                "status_checks": status_checks
            }
        
        try:
            # 确保参数格式正确
            if not commit_message:
                commit_message = f"Merge PR #{pr_number}"
            
            if not commit_title:
                commit_title = f"Merge pull request #{pr_number} from {pr.head.ref}"
            
            merge_result = pr.merge(
                commit_message=commit_message,
                commit_title=commit_title,
                merge_method=merge_method
            )
            
            return {
                "status": "success",
                "merged": merge_result.merged,
                "sha": merge_result.sha,
                "message": merge_result.message,
                "pr_number": pr_number,
                "merge_method": merge_method,
                "merged_at": merge_result.merged_at.isoformat() if hasattr(merge_result, "merged_at") and merge_result.merged_at else None,
                "token_used": token_env
            }
            
        except Exception as e:
            error_msg = str(e) if e else "未知错误"
            if not error_msg or error_msg == "None":
                error_msg = "合并失败，可能是参数错误或权限问题"
            
            # 提供更详细的错误信息
            if "Required status check" in error_msg:
                return {"error": "合并失败：必需的状态检查未通过"}
            elif "Review required" in error_msg:
                return {"error": "合并失败：需要代码审查"}
            elif "not authorized" in error_msg.lower():
                return {"error": "合并失败：没有权限合并此 PR"}
            elif "merge conflict" in error_msg.lower():
                return {"error": "合并失败：存在合并冲突"}
            elif "Base branch was modified" in error_msg:
                return {"error": "合并失败：基础分支已被修改，请更新PR"}
            elif "Pull Request is not mergeable" in error_msg:
                return {"error": "合并失败：PR不可合并"}
            else:
                return {"error": f"合并失败: {error_msg}"}
        
    except Exception as e:
        # 外层异常处理
        error_msg = str(e) if e else "未知错误"
        if not error_msg or error_msg == "None":
            error_msg = "合并PR操作失败，可能是参数错误或网络问题"
        return {"error": f"合并 PR 失败: {error_msg}"}

def check_pr_author_with_review_token(
    repo_path: str,
    pr_number: int
) -> dict:
    """
    使用审查专用Token检查 PR 作者信息
    
    Args:
        repo_path: 仓库路径，格式为 "owner/repo"
        pr_number: PR 编号
    
    Returns:
        dict: 包含 PR 作者信息和当前用户信息
    """
    try:
        # 参数验证
        if not repo_path or not isinstance(repo_path, str):
            return {"error": "repo_path 必须是有效的字符串，格式为 'owner/repo'"}
        
        if not pr_number or not isinstance(pr_number, int):
            return {"error": "pr_number 必须是有效的整数"}
        
        # 使用审查专用Token
        token_env = "REVIEW_GITHUB_TOKEN"
        token = os.getenv(token_env)
        if not token:
            return {"error": f"需要设置 {token_env} 环境变量"}
        
        g = Github(token)
        repo = g.get_repo(repo_path)
        pr = repo.get_pull(pr_number)
        
        # 获取当前用户信息
        current_user = g.get_user()
        
        # 检查是否是自己的PR
        is_own_pr = pr.user.login == current_user.login
        
        return {
            "status": "success",
            "pr_number": pr_number,
            "pr_author": pr.user.login,
            "current_user": current_user.login,
            "is_own_pr": is_own_pr,
            "pr_title": pr.title,
            "pr_state": pr.state,
            "can_approve": not is_own_pr,
            "token_used": token_env,
            "message": "这是您自己的PR，无法自己批准" if is_own_pr else "可以批准此PR"
        }
        
    except Exception as e:
        return {"error": f"检查 PR 作者失败: {str(e)}"}

def request_pr_review_with_review_token(
    repo_path: str,
    pr_number: int,
    reviewers: str = None,
    team_reviewers: str = None
) -> dict:
    """
    使用审查专用Token请求其他用户审查 PR
    
    Args:
        repo_path: 仓库路径，格式为 "owner/repo"
        pr_number: PR 编号
        reviewers: 审查者用户名列表 (JSON 字符串)（可选）
        team_reviewers: 团队审查者列表 (JSON 字符串)（可选）
    
    Returns:
        dict: 包含请求结果或错误信息
    """
    return request_pr_review(
        repo_path=repo_path,
        pr_number=pr_number,
        reviewers=reviewers,
        team_reviewers=team_reviewers,
        token_env="REVIEW_GITHUB_TOKEN"
    )

def list_prs_with_review_token(
    repo_path: str,
    state: str = "open",
    sort: str = "created",
    direction: str = "desc",
    limit: int = 20
) -> dict:
    """
    使用审查专用Token列出仓库的 PR
    
    Args:
        repo_path: 仓库路径，格式为 "owner/repo"
        state: PR 状态，可选 "open", "closed", "all"（默认 "open"）
        sort: 排序方式，可选 "created", "updated", "popularity"（默认 "created"）
        direction: 排序方向，可选 "asc", "desc"（默认 "desc"）
        limit: 最大返回数量（默认 20）
    
    Returns:
        dict: 包含 PR 列表或错误信息
    """
    return list_prs(
        repo_path=repo_path,
        state=state,
        sort=sort,
        direction=direction,
        limit=limit,
        token_env="REVIEW_GITHUB_TOKEN"
    )

def _perform_intelligent_review(pr_summary_json: str, repo) -> dict:
    """
    执行智能审查逻辑
    
    Args:
        pr_summary_json: PR 摘要信息 (JSON 字符串)
        repo: GitHub 仓库对象
    
    Returns:
        dict: 审查结果
    """
    pr_summary = json.loads(pr_summary_json)
    issues = []
    suggestions = []
    score = 100  # 满分100，扣分制
    
    # 1. 检查基本 PR 信息
    if not pr_summary["title"] or len(pr_summary["title"]) < 10:
        issues.append("PR 标题过于简单，建议提供更详细的描述")
        score -= 10
    
    if not pr_summary["body"] or len(pr_summary["body"]) < 50:
        issues.append("PR 描述过于简单，建议详细说明变更内容和原因")
        score -= 10
    
    # 2. 检查文件变更
    if pr_summary["changed_files"] == 0:
        issues.append("PR 没有文件变更")
        score -= 20
    elif pr_summary["changed_files"] > 50:
        issues.append("PR 变更文件过多，建议拆分为多个小的 PR")
        score -= 15
    
    # 3. 检查代码变更量
    if pr_summary["additions"] + pr_summary["deletions"] > 2000:
        issues.append("代码变更量较大，建议仔细审查")
        score -= 10
    
    # 4. 检查文件类型和内容
    has_tests = False
    has_docs = False
    has_code = False
    
    for file_info in pr_summary["files"]:
        filename = file_info["filename"].lower()
        
        # 检查测试文件
        if "test" in filename or filename.endswith("_test.py") or filename.endswith("test.js"):
            has_tests = True
        
        # 检查文档文件
        if filename.endswith((".md", ".rst", ".txt")) or "doc" in filename:
            has_docs = True
        
        # 检查代码文件
        if filename.endswith((".py", ".js", ".ts", ".java", ".cpp", ".c", ".go", ".rs")):
            has_code = True
            
            # 简单的代码质量检查
            patch = file_info["patch"]
            if "TODO" in patch or "FIXME" in patch:
                issues.append(f"文件 {file_info['filename']} 包含未完成的 TODO/FIXME")
                score -= 5
            
            if "print(" in patch and "test" not in filename:
                issues.append(f"文件 {file_info['filename']} 可能包含调试代码")
                score -= 3
    
    # 5. 检查测试覆盖
    if has_code and not has_tests:
        issues.append("代码变更缺少测试用例")
        score -= 15
        suggestions.append("添加相应的单元测试或集成测试")
    
    # 6. 检查文档更新
    if pr_summary["additions"] > 100 and not has_docs:
        issues.append("较大的变更缺少文档更新")
        score -= 10
        suggestions.append("更新相关文档说明变更内容")
    
    # 7. 检查合并状态
    if not pr_summary["mergeable"]:
        issues.append("PR 存在合并冲突或无法自动合并")
        score -= 20
    
    if pr_summary["mergeable_state"] == "dirty":
        issues.append("PR 有合并冲突")
        score -= 25
    elif pr_summary["mergeable_state"] == "blocked":
        issues.append("PR 被阻止合并（可能需要 CI 检查或审查）")
        score -= 15
    
    # 8. 检查是否为自己的 PR
    if pr_summary["is_own_pr"]:
        issues.append("这是您自己的 PR，需要其他用户审查才能合并")
        score -= 5  # 不扣太多分，因为这是正常情况
    
    # 生成审查总结
    summary_parts = []
    if score >= 80:
        summary_parts.append("✅ 代码质量良好")
    elif score >= 60:
        summary_parts.append("⚠️ 代码质量一般，有改进空间")
    else:
        summary_parts.append("❌ 代码质量需要改进")
    
    summary_parts.append(f"📊 审查评分: {score}/100")
    summary_parts.append(f"📁 变更文件: {pr_summary['changed_files']} 个")
    summary_parts.append(f"📝 代码行数: +{pr_summary['additions']} -{pr_summary['deletions']}")
    
    summary = "\n".join(summary_parts)
    
    # 生成修改建议
    if not suggestions and issues:
        suggestions = ["请根据上述问题进行相应修改"]
    
    # 做出决策
    if score >= 80 and not pr_summary["is_own_pr"] and pr_summary["mergeable"]:
        decision = "approve_and_merge"
    elif score >= 60:
        if pr_summary["is_own_pr"] or pr_summary["commits"] > 10 or pr_summary["changed_files"] > 20:
            decision = "request_human_review"
        else:
            decision = "approve_and_merge"
    elif score >= 40:
        decision = "request_human_review"
    else:
        decision = "request_changes"
    
    return {
        "decision": decision,
        "score": score,
        "summary": summary,
        "issues": issues,
        "suggestions": suggestions,
        "details": {
            "has_tests": has_tests,
            "has_docs": has_docs,
            "has_code": has_code,
            "mergeable": pr_summary["mergeable"],
            "mergeable_state": pr_summary["mergeable_state"]
        }
    }


def selection_sort(arr: list[float]) -> list[float]:
    """
    使用选择排序算法对数字列表进行排序。

    Args:
        arr: 数字列表。

    Returns:
        排序后的新列表。
    """
    if not isinstance(arr, list) or not all(isinstance(x, (int, float)) for x in arr):
        raise TypeError("输入必须是数字列表")

    sorted_arr = arr.copy()
    n = len(sorted_arr)
    for i in range(n):
        min_idx = i
        for j in range(i + 1, n):
            if sorted_arr[j] < sorted_arr[min_idx]:
                min_idx = j
        sorted_arr[i], sorted_arr[min_idx] = sorted_arr[min_idx], sorted_arr[i]
    return sorted_arr

def list_branches(repo_path: str, token_env: str = "GITHUB_TOKEN") -> dict:
    """
    获取指定仓库的分支列表

    Args:
        repo_path: 仓库路径，格式为 "owner/repo"
        token_env: GitHub Token 环境变量名（默认 "GITHUB_TOKEN"）

    Returns:
        dict: 包含分支列表或错误信息
    """
    try:
        token = os.getenv(token_env)
        g = Github(token) if token else Github()
        repo = g.get_repo(repo_path)
        branches = repo.get_branches()
        branch_list = [branch.name for branch in branches]
        return {
            "status": "success",
            "repo": repo_path,
            "branches": branch_list
        }
    except Exception as e:
        return {"error": f"获取分支列表失败: {str(e)}"}
